# site settings
title: Open Banking
subtitle: Space
email: youremailaddress@gmail.com
description: 
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
domain: blog.openbanking.space

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# build settings
markdown: kramdown

sass:
  style: compressed
